name: lint
on:
  push:
  workflow_call:
    secrets:
      API_DEPLOY_KEY:
        required: true
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.6'
      - name: Install dependencies
        run: /bin/bash scripts/install_build_deps.sh
      - name: make lint
        run: make lint
